# Generated by Django 2.0.7 on 2018-09-05 22:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatterGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('at_bats', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('runs_batted_in', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('stolen_bases', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('left_on_base', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('yahoo_id', models.IntegerField(unique=True)),
                ('start', models.DateField(db_index=True, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('progress', models.CharField(max_length=6, null=True)),
                ('home_runs', models.IntegerField(default=0)),
                ('away_runs', models.IntegerField(default=0)),
                ('home_hits', models.IntegerField(default=0)),
                ('away_hits', models.IntegerField(default=0)),
                ('home_errors', models.IntegerField(default=0)),
                ('away_errors', models.IntegerField(default=0)),
                ('innings', models.IntegerField(default=0)),
                ('inning_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PitcherGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('innings', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('earned_runs', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('yahoo_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25)),
                ('suffix', models.CharField(max_length=5, null=True)),
                ('dob', models.DateField(null=True)),
                ('number', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('abbr', models.CharField(max_length=3)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=3)),
                ('logo_sm', models.CharField(max_length=100)),
                ('logo_lg', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=1)),
                ('division', models.CharField(max_length=1)),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Park')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Team'),
        ),
        migrations.AddField(
            model_name='pitchergame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_pitcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_pitcher', to='data.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='data.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_pitcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_pitcher', to='data.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='data.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='park',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Park'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.GameStatus'),
        ),
        migrations.AddField(
            model_name='battergame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Game'),
        ),
        migrations.AddField(
            model_name='battergame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player'),
        ),
        migrations.AddField(
            model_name='battergame',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Team'),
        ),
    ]
