# Generated by Django 2.0.7 on 2018-09-11 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchergame',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pitchergame',
            name='innings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
