# Generated by Django 2.0.7 on 2018-09-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180911_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchergame',
            name='pitches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitchergame',
            name='strikes',
            field=models.IntegerField(default=0),
        ),
    ]
