# Generated by Django 2.0.7 on 2018-09-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180911_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchergame',
            name='blown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitchergame',
            name='hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitchergame',
            name='loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitchergame',
            name='save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitchergame',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
