# Generated by Django 2.0.7 on 2018-09-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180912_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitchergame',
            old_name='save',
            new_name='sv',
        ),
    ]
