# Generated by Django 2.0.7 on 2018-09-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180912_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchergame',
            name='batters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitchergame',
            name='fly_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitchergame',
            name='ground_balls',
            field=models.IntegerField(default=0),
        ),
    ]
