# Generated by Django 2.0.7 on 2018-09-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180912_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchergame',
            name='spot',
            field=models.IntegerField(default=0),
        ),
    ]
