# Generated by Django 2.0.7 on 2018-09-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_pitchergame_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchergame',
            name='outs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitchergame',
            name='whole_innings',
            field=models.IntegerField(default=0),
        ),
    ]
