openapi: 3.0.0
info:
  title: monitor_methods
  description: monitor_methods
  version: "1.0.0"

# Paths supported by the server application
paths:
  /register:
    post:
      operationId: monitor_wtf.register
      tags:
        - Register
      summary: Register an application
      description: Get the next available id, associate it with the application, register the app, return the id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                appName:
                  type: string
                  example: reporting
      responses:
        200:
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
